baseurl:    /CVbyDL-Object-Property-Inference
locale:     "en"
title:      Weight inference from object images
tagline:    A blog for the Computer Vision by Deep Learning course
writers:    Koen du Buf and Olivier Dikken

author:
  name:     Koen du Buf
  url:      https://github.com/KoenduBuf
